version: '3'
services:
  # Node.js Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      MONGODB_URI: mongodb://mongo:27017/ipsee
    depends_on:
      - mongo
    networks:
      - ipsee_network

  # Flask API Service
  flask_api:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_api
    restart: always
    networks:
      - ipsee_network

  # MongoDB Service
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ipsee_network

  # Nginx Service for reverse proxy and SSL
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - flask_api
    networks:
      - ipsee_network

# Docker volumes to persist MongoDB data
volumes:
  mongo-data:

# Define a custom Docker network
networks:
  ipsee_network:
    driver: bridge
