# Use Python 3.9 as the base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy requirements.txt and install Python dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Download the spaCy model 'en_core_web_sm'
RUN python -m spacy download en_core_web_sm

# Copy the rest of the Python source code
COPY . .

# Expose port 5000 for the Flask API
EXPOSE 5000

# Start the Flask app
CMD ["python", "nlp_api.py"]
